#sr: 8

#rank_status: ranked

#sr: 10

#ln_ratio: 0
#
#rc: 1
#ln: 0
#hb: 0

#ln_ratio: 0.3


#sr: 5

#chordjack: 1
###chordjack_ett: 31
#######
####stamina: 1
#######stamin_ett: 23
#######
#stream: 1
########stream_ett: 15
#######
#jumpstream: 0
#######jumpstream_ett: 27
#######
#handstream: 0
########handstream_ett: 15
#######
#jackspeed: 0
########jackspeed_ett: 14
#######
technical: 1
#technical_ett: 35

ln: 0
###
rc: 1
##
hb: 0

ln_ratio: 0
