- name: sr
  type: numeric
  min: 1
  max: 8
  interval: 0.2

#- name: rank_status
#  type: category
#  category:
#    - ranked, rank
#    - loved, love

- name: ln_ratio
  type: numeric
  min: 0
  max: 1
  interval: 0.1

- name: rc
  type: bool

- name: hb
  type: bool

- name: ln
  type: bool


# TODO: mapper
# TODO: minacalc
# TODO: diff name